name: Test and Publish

on: [push, pull_request]


jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        os: [
          "ubuntu-latest",
          "macOS-latest",
          "windows-latest"
        ]
        python-version: [
          "3.7",
        ]
        # only test x64 for now as it supports all features on all platforms
        architecture: ["x64"]
    
    timeout-minutes: 30

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} ${{ matrix.architecture }} - ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade wheel setuptools twine
        pip install pytest
        pip install git+https://github.com/pythonnet/pythonnet.git
    
    - name: Install AssetStudioPy
      run: |
        python setup.py install

    - name: Test with pytest
      run: |
        python tests/test.py

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_${{ matrix.architecture }}_CN_021.wav
        path: ${{github.workspace}}/tests/extracted/CN_021_live.wav